# Generated by Django 5.0.1 on 2026-01-14 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUnit",
            fields=[
                (
                    "admin_unit_id",
                    models.CharField(
                        help_text="Unique identifier for the administrative unit",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "admin_unit_type",
                    models.CharField(
                        choices=[
                            ("National", "National"),
                            ("Region", "Region"),
                            ("Zone", "Zone"),
                            ("Sub-city", "Sub-city"),
                            ("Woreda", "Woreda"),
                            ("Center-Cluster", "Center-Cluster"),
                        ],
                        db_index=True,
                        help_text="Type of administrative unit (Region, Zone, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "admin_unit_name_en",
                    models.CharField(
                        db_index=True,
                        help_text="Administrative unit name in English",
                        max_length=255,
                    ),
                ),
                (
                    "admin_unit_name_am",
                    models.CharField(
                        blank=True,
                        help_text="Administrative unit name in Amharic",
                        max_length=255,
                    ),
                ),
                (
                    "admin_unit_code",
                    models.CharField(
                        blank=True,
                        help_text="Short code for the administrative unit",
                        max_length=20,
                    ),
                ),
                (
                    "jurisdiction_path",
                    models.CharField(
                        blank=True,
                        help_text='Full path from root to this unit (e.g., "National > Oromia > East Shewa Zone")',
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Status of the administrative unit",
                        max_length=20,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        blank=True,
                        help_text="Date from which this unit is effective",
                        null=True,
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Date until which this unit is effective (null = indefinite)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="User ID who created this unit",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this unit was created",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="User ID who last updated this unit",
                        max_length=50,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this unit was last updated",
                    ),
                ),
                (
                    "parent_admin_unit_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_admin_unit_id",
                        help_text="Parent administrative unit (for hierarchical structure)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="governance.adminunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Unit",
                "verbose_name_plural": "Administrative Units",
                "db_table": "admin_units",
                "ordering": ["admin_unit_type", "admin_unit_name_en"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "institution_id",
                    models.CharField(
                        help_text="Unique identifier for the institution",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("Government", "Government"),
                            ("Partner", "Partner"),
                            ("Private", "Private"),
                        ],
                        db_index=True,
                        help_text="Type of institution",
                        max_length=20,
                    ),
                ),
                (
                    "institution_name_en",
                    models.CharField(
                        db_index=True,
                        help_text="Institution name in English",
                        max_length=255,
                    ),
                ),
                (
                    "institution_name_am",
                    models.CharField(
                        blank=True,
                        help_text="Institution name in Amharic",
                        max_length=255,
                    ),
                ),
                (
                    "institution_short_name",
                    models.CharField(
                        blank=True, help_text="Short name or acronym", max_length=50
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Official registration number",
                        max_length=100,
                    ),
                ),
                (
                    "contact_person_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact person name",
                        max_length=255,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "address_text",
                    models.TextField(blank=True, help_text="Physical address"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Status of the institution",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="region_id",
                        help_text="Primary region for this institution",
                        limit_choices_to={"admin_unit_type": "Region"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institutions",
                        to="governance.adminunit",
                    ),
                ),
            ],
            options={
                "db_table": "institutions",
                "ordering": ["institution_name_en"],
            },
        ),
        migrations.AddIndex(
            model_name="adminunit",
            index=models.Index(
                fields=["admin_unit_type", "status"],
                name="admin_units_admin_u_8e8fec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminunit",
            index=models.Index(
                fields=["parent_admin_unit_id", "status"],
                name="admin_units_parent__386060_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminunit",
            index=models.Index(
                fields=["-created_at"], name="admin_units_created_12742a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["institution_type", "status"],
                name="institution_institu_d2bf9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["region_id", "status"], name="institution_region__f355cc_idx"
            ),
        ),
    ]
