# Generated by Django 5.0.1 on 2026-01-14 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminunit",
            name="admin_unit_id",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for the administrative unit (auto-generated from name if not provided)",
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="adminunit",
            name="admin_unit_type",
            field=models.CharField(
                choices=[
                    ("Region", "Region"),
                    ("Zone", "Zone"),
                    ("Woreda", "Woreda"),
                    ("Kebele", "Kebele"),
                    ("National", "National"),
                    ("Sub-city", "Sub-city"),
                    ("Center-Cluster", "Center-Cluster"),
                ],
                db_index=True,
                help_text="Type of administrative unit (Region, Zone, etc.)",
                max_length=20,
            ),
        ),
    ]
