# Generated by Django 5.0.1 on 2026-01-14 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0002_alter_adminunit_admin_unit_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminunit",
            name="admin_unit_id",
            field=models.CharField(
                help_text="Unique identifier for the administrative unit (auto-generated from name if not provided)",
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
