# Generated by Django 5.0.1 on 2026-01-01 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                (
                    "user_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_LOGIN", "User Login"),
                            ("USER_LOGOUT", "User Logout"),
                            ("USER_CREATED", "User Created"),
                            ("USER_UPDATED", "User Updated"),
                            ("USER_DELETED", "User Deleted"),
                            ("USER_SUSPENDED", "User Suspended"),
                            ("USER_ACTIVATED", "User Activated"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("ROLE_CREATED", "Role Created"),
                            ("ROLE_UPDATED", "Role Updated"),
                            ("ROLE_DELETED", "Role Deleted"),
                            ("ROLE_ASSIGNED", "Role Assigned"),
                            ("CENTER_CREATED", "Center Created"),
                            ("CENTER_UPDATED", "Center Updated"),
                            ("CENTER_DELETED", "Center Deleted"),
                            ("CENTER_GEOFENCE_UPDATED", "Center Geofence Updated"),
                            ("INSPECTION_CREATED", "Inspection Created"),
                            ("INSPECTION_UPDATED", "Inspection Updated"),
                            ("INSPECTION_COMPLETED", "Inspection Completed"),
                            ("INSPECTION_FAILED", "Inspection Failed"),
                            ("FAILED_LOGIN", "Failed Login Attempt"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity Detected"),
                            ("GEOFENCE_VIOLATION", "Geofence Violation"),
                            ("SYSTEM_CONFIG_CHANGED", "System Configuration Changed"),
                            ("DATA_EXPORT", "Data Exported"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(db_index=True, max_length=50)),
                ("resource_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SuspiciousActivity",
            fields=[
                (
                    "activity_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("RAPID_ACTIONS", "Rapid Actions"),
                            ("UNUSUAL_LOCATION", "Unusual Location"),
                            ("AFTER_HOURS", "After Hours Activity"),
                            ("MULTIPLE_FAILED_LOGINS", "Multiple Failed Logins"),
                            ("GEOFENCE_VIOLATION", "Geofence Violation"),
                            ("UNUSUAL_PATTERN", "Unusual Pattern"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "risk_score",
                    models.IntegerField(default=0, help_text="Risk score 0-100"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("RESOLVED", "Resolved"),
                            ("FALSE_POSITIVE", "False Positive"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "related_logs",
                    models.ManyToManyField(
                        related_name="suspicious_activities", to="security.auditlog"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspicious_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Suspicious Activities",
                "db_table": "suspicious_activities",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_logs_user_id_88267f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="audit_logs_action_474804_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="audit_logs_resourc_bda8a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="suspiciousactivity",
            index=models.Index(
                fields=["status", "detected_at"], name="suspicious__status_881ead_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suspiciousactivity",
            index=models.Index(
                fields=["user", "activity_type"], name="suspicious__user_id_85d696_idx"
            ),
        ),
    ]
