# Generated by Django 5.0.1 on 2025-12-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "center_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("region", models.CharField(db_index=True, max_length=100)),
                ("zone", models.CharField(blank=True, max_length=100)),
                ("subcity", models.CharField(blank=True, max_length=100)),
                ("woreda", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "geofence_radius_meters",
                    models.IntegerField(
                        default=500, help_text="Geofence radius in meters"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("attention_score", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("total_inspections", models.IntegerField(default=0)),
                ("last_inspection_date", models.DateTimeField(blank=True, null=True)),
                (
                    "pass_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Pass rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "average_cycle_time_minutes",
                    models.IntegerField(
                        default=0, help_text="Average inspection cycle time"
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "centers",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["region", "status"], name="centers_region_3ae5f6_idx"
                    ),
                    models.Index(
                        fields=["-attention_score"], name="centers_attenti_e38bd0_idx"
                    ),
                ],
            },
        ),
    ]
