# Generated by Django 5.0.1 on 2026-01-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="business_license_date_of_issuance",
            field=models.DateField(
                blank=True, help_text="Business License Date of Issuance", null=True
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="business_license_no",
            field=models.CharField(
                blank=True, help_text="Business License Number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="camera_configuration",
            field=models.TextField(blank=True, help_text="Camera Configuration"),
        ),
        migrations.AddField(
            model_name="center",
            name="capital_in_etb",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Capital in ETB",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="commercial_registration_procedure",
            field=models.TextField(
                blank=True, help_text="Commercial Registration Procedure"
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="date_of_issue",
            field=models.DateField(blank=True, help_text="Date of Issue", null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="fax",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="center",
            name="field_of_business",
            field=models.CharField(
                blank=True, help_text="Field of Business", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="general_manager_name",
            field=models.CharField(
                blank=True, help_text="General Manager Name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="house_no",
            field=models.CharField(blank=True, help_text="House Number", max_length=50),
        ),
        migrations.AddField(
            model_name="center",
            name="kebele",
            field=models.CharField(blank=True, help_text="Kebele", max_length=100),
        ),
        migrations.AddField(
            model_name="center",
            name="nationality",
            field=models.CharField(blank=True, help_text="Nationality", max_length=100),
        ),
        migrations.AddField(
            model_name="center",
            name="owner_company_name",
            field=models.CharField(
                blank=True, help_text="Owner/Company Name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="place_of_issue",
            field=models.CharField(
                blank=True, help_text="Place of Issue", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="principal_registration_no",
            field=models.CharField(
                blank=True, help_text="Principal Registration Number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="telebirr_number",
            field=models.CharField(
                blank=True, help_text="TeleBirr Number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="tin",
            field=models.CharField(
                blank=True, help_text="Tax Identification Number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="trade_name",
            field=models.CharField(blank=True, help_text="Trade Name", max_length=255),
        ),
        migrations.AddField(
            model_name="center",
            name="vat",
            field=models.CharField(blank=True, help_text="VAT Number", max_length=50),
        ),
    ]
