# Generated by Django 5.0.1 on 2026-01-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centers", "0002_center_business_license_date_of_issuance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="business_license_document",
            field=models.FileField(
                blank=True,
                help_text="Business License Document",
                null=True,
                upload_to="centers/documents/business_license/",
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="other_documents",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of other document file paths/URLs",
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="registration_certificate_document",
            field=models.FileField(
                blank=True,
                help_text="Registration Certificate Document",
                null=True,
                upload_to="centers/documents/registration_certificate/",
            ),
        ),
        migrations.AddField(
            model_name="center",
            name="tax_certificate_document",
            field=models.FileField(
                blank=True,
                help_text="Tax Certificate Document",
                null=True,
                upload_to="centers/documents/tax_certificate/",
            ),
        ),
    ]
