# Generated by Django 5.0.1 on 2026-01-12 07:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "fee_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("vehicle_category", models.CharField(max_length=10)),
                ("vehicle_type", models.CharField(blank=True, max_length=50)),
                (
                    "inspection_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "retest_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fee_structures",
                "ordering": ["vehicle_category", "vehicle_type"],
            },
        ),
        migrations.CreateModel(
            name="TestStandard",
            fields=[
                (
                    "standard_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "vehicle_category",
                    models.CharField(
                        choices=[
                            ("LIGHT", "Light Vehicle"),
                            ("HEAVY", "Heavy Vehicle"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("emissions", "Emissions Test"),
                            ("headlight", "Headlight Test"),
                            ("brake", "Brake Test"),
                            ("suspension", "Suspension Test"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "test_standards",
                "ordering": ["vehicle_category", "test_type"],
            },
        ),
        migrations.CreateModel(
            name="VisualChecklistConfig",
            fields=[
                (
                    "config_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "vehicle_category",
                    models.CharField(
                        choices=[
                            ("LIGHT", "Light Vehicle"),
                            ("HEAVY", "Heavy Vehicle"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("zone_id", models.CharField(db_index=True, max_length=20)),
                ("zone_name_en", models.CharField(max_length=100)),
                ("zone_name_am", models.CharField(blank=True, max_length=100)),
                (
                    "item_number",
                    models.IntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("item_name_en", models.CharField(max_length=200)),
                ("item_name_am", models.CharField(blank=True, max_length=200)),
                (
                    "points_possible",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Critical items cause automatic failure if failed",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True, help_text="Mandatory items must be checked"
                    ),
                ),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_checklist_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "visual_checklist_configs",
                "ordering": [
                    "vehicle_category",
                    "zone_id",
                    "display_order",
                    "item_number",
                ],
                "indexes": [
                    models.Index(
                        fields=["vehicle_category", "status"],
                        name="visual_chec_vehicle_708be9_idx",
                    ),
                    models.Index(
                        fields=["zone_id", "display_order"],
                        name="visual_chec_zone_id_bf44d2_idx",
                    ),
                ],
                "unique_together": {("vehicle_category", "zone_id", "item_number")},
            },
        ),
    ]
