# Generated by Django 5.0.1 on 2025-12-26 08:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlignmentTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alignment_deviation",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("alignment_pass", models.BooleanField()),
                (
                    "suspension_left",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "suspension_right",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "suspension_diff",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("suspension_pass", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "alignment_tests",
            },
        ),
        migrations.CreateModel(
            name="BrakeTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brake_type",
                    models.CharField(
                        choices=[
                            ("service", "Service Brake"),
                            ("parking", "Parking Brake"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "front_left_force",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "front_right_force",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "front_balance",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "rear_left_force",
                    models.DecimalField(decimal_places=1, max_digits=7),
                ),
                (
                    "rear_right_force",
                    models.DecimalField(decimal_places=1, max_digits=7),
                ),
                ("rear_balance", models.DecimalField(decimal_places=1, max_digits=5)),
                ("total_force", models.DecimalField(decimal_places=1, max_digits=7)),
                ("force_pass", models.BooleanField()),
                ("balance_pass", models.BooleanField()),
                ("overall_pass", models.BooleanField()),
            ],
            options={
                "db_table": "brake_tests",
            },
        ),
        migrations.CreateModel(
            name="EmissionsTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emission_type",
                    models.CharField(
                        choices=[
                            ("gas_analyzer", "Gas Analyzer (Petrol)"),
                            ("smoke_meter", "Smoke Meter (Diesel)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hc",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=6, null=True
                    ),
                ),
                (
                    "co",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "co2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "o2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "lambda_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "opacity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("overall_pass", models.BooleanField()),
            ],
            options={
                "db_table": "emissions_tests",
            },
        ),
        migrations.CreateModel(
            name="HeadlightTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left_intensity", models.DecimalField(decimal_places=0, max_digits=8)),
                (
                    "left_aim_horizontal",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "left_aim_vertical",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("left_pass", models.BooleanField()),
                (
                    "right_intensity",
                    models.DecimalField(decimal_places=0, max_digits=8),
                ),
                (
                    "right_aim_horizontal",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "right_aim_vertical",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("right_pass", models.BooleanField()),
                ("overall_pass", models.BooleanField()),
            ],
            options={
                "db_table": "headlight_tests",
            },
        ),
        migrations.CreateModel(
            name="InspectionPhoto",
            fields=[
                (
                    "photo_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration Photo"),
                            ("visual_inspection", "Visual Inspection Evidence"),
                            ("machine_test", "Machine Test Evidence"),
                            ("defect", "Defect Documentation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("photo_url", models.URLField(max_length=500)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inspection_photos",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="InspectionVideo",
            fields=[
                (
                    "video_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("video_url", models.URLField(max_length=500)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inspection_videos",
            },
        ),
        migrations.CreateModel(
            name="MachineTest",
            fields=[
                (
                    "machine_test_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("alignment", "Alignment & Suspension"),
                            ("service_brake", "Service Brake"),
                            ("parking_brake", "Parking Brake"),
                            ("gas_analyzer", "Gas Analyzer"),
                            ("smoke_meter", "Smoke Meter"),
                            ("headlight", "Headlight Test"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("test_name", models.CharField(max_length=100)),
                ("test_data", models.JSONField(help_text="Raw machine data")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("NA", "Not Applicable"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pass_status", models.BooleanField()),
                (
                    "data_source",
                    models.CharField(default="Machine_Interface", max_length=50),
                ),
                ("machine_serial", models.CharField(blank=True, max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=True, help_text="Machine data cannot be edited"
                    ),
                ),
            ],
            options={
                "db_table": "machine_tests",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="VisualChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                ("item_name_en", models.CharField(max_length=100)),
                ("item_name_am", models.CharField(max_length=100)),
                ("zone_id", models.CharField(max_length=20)),
                ("zone_name_en", models.CharField(max_length=100)),
                ("points_possible", models.IntegerField()),
                ("points_earned", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "Correct"),
                            ("FAIL", "Not Correct"),
                            ("NA", "Not Applicable"),
                        ],
                        max_length=10,
                    ),
                ),
                ("defect_type", models.CharField(blank=True, max_length=50)),
                ("is_critical", models.BooleanField(default=False)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "visual_checklist_items",
                "ordering": ["item_number"],
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "inspection_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}-?\\d{4,5}[A-Z]?$"
                            )
                        ],
                    ),
                ),
                ("chassis_number", models.CharField(db_index=True, max_length=50)),
                ("engine_number", models.CharField(max_length=50)),
                ("vehicle_type", models.CharField(max_length=50)),
                (
                    "vehicle_category",
                    models.CharField(
                        choices=[
                            ("LIGHT", "Light Vehicle"),
                            ("HEAVY", "Heavy Vehicle"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("brand_model", models.CharField(max_length=100)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("Electric", "Electric"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kilometer_reading",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "licensed_capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("title_certificate", models.CharField(max_length=50)),
                ("owner_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("pending_machine", "Pending Machine Tests"),
                            ("pending_payment", "Pending Payment"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("overall_result", models.CharField(blank=True, max_length=10)),
                ("visual_points_earned", models.IntegerField(default=0)),
                ("visual_points_total", models.IntegerField(default=0)),
                ("visual_pass", models.BooleanField(null=True)),
                ("machine_test_pass", models.BooleanField(null=True)),
                (
                    "payment_status",
                    models.CharField(db_index=True, default="unpaid", max_length=20),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("form_id", models.CharField(max_length=50)),
                ("test_start_time", models.DateTimeField()),
                ("test_end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to="centers.center",
                    ),
                ),
            ],
            options={
                "db_table": "inspections",
                "ordering": ["-created_at"],
            },
        ),
    ]
