# Generated by Django 5.0.1 on 2025-12-26 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inspections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="inspector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspections_conducted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inspectionphoto",
            name="inspection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="inspections.inspection",
            ),
        ),
        migrations.AddField(
            model_name="inspectionvideo",
            name="inspection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="inspections.inspection",
            ),
        ),
        migrations.AddField(
            model_name="machinetest",
            name="inspection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machine_tests",
                to="inspections.inspection",
            ),
        ),
        migrations.AddField(
            model_name="headlighttest",
            name="machine_test",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="headlight_details",
                to="inspections.machinetest",
            ),
        ),
        migrations.AddField(
            model_name="emissionstest",
            name="machine_test",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emissions_details",
                to="inspections.machinetest",
            ),
        ),
        migrations.AddField(
            model_name="braketest",
            name="machine_test",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brake_details",
                to="inspections.machinetest",
            ),
        ),
        migrations.AddField(
            model_name="alignmenttest",
            name="machine_test",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alignment_details",
                to="inspections.machinetest",
            ),
        ),
        migrations.AddField(
            model_name="visualchecklistitem",
            name="inspection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visual_items",
                to="inspections.inspection",
            ),
        ),
        migrations.AddField(
            model_name="inspectionphoto",
            name="visual_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="inspections.visualchecklistitem",
            ),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["center", "created_at"], name="inspections_center__4d0ad1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["inspector", "status", "created_at"],
                name="inspections_inspect_78a085_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["plate_number", "created_at"],
                name="inspections_plate_n_5cb6ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(
                fields=["status", "overall_result"],
                name="inspections_status_cc3d9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="machinetest",
            index=models.Index(
                fields=["inspection", "test_type"],
                name="machine_tes_inspect_d6bb82_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visualchecklistitem",
            unique_together={("inspection", "item_number")},
        ),
    ]
