# Generated by Django 5.0.1 on 2025-12-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspection",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspection",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="inspection",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="inspection",
            name="sync_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inspection",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
