# Generated by Django 5.0.1 on 2026-01-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inspections",
            "0003_inspection_completed_at_inspection_payment_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionphoto",
            name="photo_url",
            field=models.TextField(),  # No max_length for TextField
        ),
    ]
