# Generated by Django 5.0.1 on 2026-01-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0004_alter_inspectionphoto_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionphoto",
            name="photo_url",
            field=models.TextField(),
        ),
    ]
