# Generated by Django 5.0.1 on 2026-01-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0005_alter_inspectionphoto_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionphoto",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inspectionphoto",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=30, null=True
            ),
        ),
    ]
