# Generated by Django 5.0.1 on 2026-01-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0006_alter_inspectionphoto_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinetest",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("alignment", "Alignment"),
                    ("suspension", "Suspension"),
                    ("service_brake", "Service Brake"),
                    ("parking_brake", "Parking Brake"),
                    ("gas_analyzer", "Gas Analyzer"),
                    ("smoke_meter", "Smoke Meter"),
                    ("headlight", "Headlight Test"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
