# Generated by Django 5.0.1 on 2026-01-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0007_alter_machinetest_test_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="plate_number",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
