# Generated by Django 5.0.1 on 2026-02-19 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0008_alter_inspection_plate_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="kilometer_reading",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="vehicle_category",
            field=models.CharField(
                choices=[
                    ("LIGHT", "Light Vehicle"),
                    ("HEAVY", "Heavy Vehicle"),
                    ("MOTOR", "Motor / 3-Wheel"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
