# Generated by Django 5.0.1 on 2025-12-26 08:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "role_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("role_name_en", models.CharField(max_length=100)),
                ("role_name_am", models.CharField(blank=True, max_length=100)),
                (
                    "role_category",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Audit", "Audit"),
                            ("Operations", "Operations"),
                            ("Enforcement", "Enforcement"),
                            ("ReadOnly", "Read Only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_scope_type",
                    models.CharField(
                        choices=[
                            ("National", "National"),
                            ("Regional", "Regional"),
                            ("Zone", "Zone"),
                            ("SubCity", "Sub-City"),
                            ("Woreda", "Woreda"),
                            ("Center", "Center"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_sensitive_role", models.BooleanField(default=False)),
                ("two_person_approval_required", models.BooleanField(default=False)),
                ("permissions", models.JSONField(default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "roles",
                "ordering": ["role_category", "role_name_en"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?\\d{10,15}$")
                        ],
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Suspended", "Suspended"),
                            ("Disabled", "Disabled"),
                            ("Pending", "Pending Activation"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("mfa_enrolled", models.BooleanField(default=False)),
                ("mfa_secret", models.CharField(blank=True, max_length=32)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("account_locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DelegationPolicy",
            fields=[
                (
                    "delegation_policy_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "allowed_roles_to_assign",
                    models.JSONField(
                        default=list, help_text="List of role IDs that can be assigned"
                    ),
                ),
                (
                    "max_scope_level",
                    models.CharField(
                        help_text="Maximum scope level that can be assigned",
                        max_length=100,
                    ),
                ),
                ("requires_approval_for_sensitive", models.BooleanField(default=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegator_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegation_policies",
                        to="users.role",
                    ),
                ),
            ],
            options={
                "db_table": "delegation_policies",
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "role_assignment_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("National", "National"),
                            ("Regional", "Regional"),
                            ("Zone", "Zone"),
                            ("SubCity", "Sub-City"),
                            ("Woreda", "Woreda"),
                            ("Center", "Center"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "scope_ids",
                    models.JSONField(
                        default=list, help_text="List of admin unit IDs in scope"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("PendingApproval", "Pending Approval"),
                            ("Revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("approval_required", models.BooleanField(default=False)),
                (
                    "approval_status",
                    models.CharField(default="Approved", max_length=20),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="users.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "role_assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["status", "is_active"], name="users_status_1462fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username", "email"], name="users_usernam_71eb2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(
                fields=["user", "status"], name="role_assign_user_id_541f3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(
                fields=["role", "scope_type"], name="role_assign_role_id_f29dd3_idx"
            ),
        ),
    ]
